# This is a basic workflow to help you get started with Actions

name: run_main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run main
          source /venv/bin/activate
          python3 -o ./github/workflows/test/*.py

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: bat-run
        run: |
          /venv/bin/activate.bat
          python3 -o .github/workflows/test/*.py
      - name: ps1-run
        if: ${{ failure() }}
        run: |
          /venv/bin/activate.ps1
          python3 -o .github/workflows/test/*.py

