# This is a basic workflow to help you get started with Actions

name: run_main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        run: |
          source ./venv/bin/activate
          python3 -o ./.github/workflows/test/*.py

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: bat-run
        run: |
          ./venv/bin/activate.bat
          python3 -o ./.github/workflows/test/*.py

        if: ${{ failure() }}
      - uses: actions/checkout@v2
      - name: ps1-run
        run: |
          ./venv/bin/activate.ps1
          python3 -o ./.github/workflows/test/*.py

