# This is a basic workflow to help you get started with Actions

name: run_main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run main
        run: |
          source venv/bin/activate
          python3 -o main

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: run main
        run: |
          source venv/bin/activate
          python3 -o main
