# This is a basic workflow to help you get started with Actions

name: run_main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: bash-run
      continue-on-error: true
      - uses: actions/checkout@v2
        run: |
          pip3 install tkinter
          pip3 install matplotlib
          python3 -O test.py

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: bat-run
        run: |
          pip3 install matplotlib
          python3 -O test.py

        if: ${{ failure() }}
      - uses: actions/checkout@v2
      - name: ps1-run
        run: |
          pip3 install matplotlib
          python3 -O test.py

